apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.getdbservicename" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ include "mysql.fullname" . }}
  type: {{ .Values.service.type }}

